packages:
  - configs/*
  - packages/*
  - projects/*

catalog:
  '@ant-design/icons': ^6.1.0
  '@eslint/js': ^9.39.2
  '@fluentui/react-accordion': 9.8.7
  '@fluentui/react-alert': 9.0.0-beta.124
  '@fluentui/react-aria': 9.17.1
  '@fluentui/react-avatar': 9.9.7
  '@fluentui/react-badge': 9.4.6
  '@fluentui/react-breadcrumb': 9.3.7
  '@fluentui/react-button': 9.6.7
  '@fluentui/react-card': 9.5.1
  '@fluentui/react-carousel': 9.8.7
  '@fluentui/react-checkbox': 9.5.6
  '@fluentui/react-color-picker': 9.2.6
  '@fluentui/react-combobox': 9.16.7
  '@fluentui/react-components': 9.71.0
  '@fluentui/react-context-selector': 9.2.8
  '@fluentui/react-dialog': 9.15.2
  '@fluentui/react-divider': 9.4.6
  '@fluentui/react-drawer': 9.10.2
  '@fluentui/react-field': 9.4.6
  '@fluentui/react-image': 9.3.6
  '@fluentui/react-infobutton': 9.0.0-beta.102
  '@fluentui/react-infolabel': 9.4.7
  '@fluentui/react-input': 9.7.6
  '@fluentui/react-jsx-runtime': 9.2.1
  '@fluentui/react-label': 9.3.6
  '@fluentui/react-link': 9.6.6
  '@fluentui/react-list': 9.6.1
  '@fluentui/react-menu': 9.20.0
  '@fluentui/react-message-bar': 9.6.7
  '@fluentui/react-motion': 9.11.0
  '@fluentui/react-motion-components-preview': 0.10.1
  '@fluentui/react-nav': 9.3.7
  '@fluentui/react-overflow': 9.6.0
  '@fluentui/react-persona': 9.5.7
  '@fluentui/react-popover': 9.12.7
  '@fluentui/react-portal': 9.8.3
  '@fluentui/react-positioning': 9.20.6
  '@fluentui/react-progress': 9.4.6
  '@fluentui/react-provider': 9.22.6
  '@fluentui/react-radio': 9.5.6
  '@fluentui/react-rating': 9.3.6
  '@fluentui/react-search': 9.3.6
  '@fluentui/react-select': 9.4.6
  '@fluentui/react-shared-contexts': 9.25.2
  '@fluentui/react-skeleton': 9.4.6
  '@fluentui/react-slider': 9.5.6
  '@fluentui/react-spinbutton': 9.5.6
  '@fluentui/react-spinner': 9.7.6
  '@fluentui/react-swatch-picker': 9.4.6
  '@fluentui/react-switch': 9.4.6
  '@fluentui/react-table': 9.19.0
  '@fluentui/react-tabs': 9.10.2
  '@fluentui/react-tabster': 9.26.6
  '@fluentui/react-tag-picker': 9.7.7
  '@fluentui/react-tags': 9.7.7
  '@fluentui/react-teaching-popover': 9.6.7
  '@fluentui/react-text': 9.6.6
  '@fluentui/react-textarea': 9.6.6
  '@fluentui/react-theme': 9.2.0
  '@fluentui/react-toast': 9.7.2
  '@fluentui/react-toolbar': 9.6.7
  '@fluentui/react-tooltip': 9.8.6
  '@fluentui/react-tree': 9.14.0
  '@fluentui/react-utilities': 9.25.0
  '@fluentui/react-virtualizer': 9.0.0-alpha.102
  '@griffel/react': 1.5.22
  '@jest/globals': ^30.2.0
  '@jest/types': ^30.2.0
  '@nestjs/common': ^11.1.11
  '@nestjs/core': ^11.1.11
  '@nestjs/jwt': ^11.0.2
  '@reduxjs/toolkit': ^2.11.2
  '@rustresult/result': ^0.6.0
  '@swc/helpers': 0.5.1
  '@swc/jest': ^0.2.39
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@types/confusing-browser-globals': ^1.0.3
  '@types/express': ^5.0.6
  '@types/node': ^24.10.4
  '@types/prompts': ^2.4.9
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@types/react-is': ^19.2.0
  '@types/semver': ^7.7.1
  '@vitejs/plugin-react': ^5.1.2
  antd: 6.1.4
  browserslist: ^4.28.1
  browserslist-to-esbuild: ^2.1.1
  bundlemon: ^3.1.0
  camelcase: ^9.0.0
  chalk: ^5.6.2
  class-transformer: ^0.5.1
  class-validator: ^0.14.3
  clsx: ^2.1.1
  commander: ^14.0.2
  concurrently: ^9.2.1
  confusing-browser-globals: ^1.0.11
  copyfiles: ^2.4.1
  cross-env: ^10.1.0
  dayjs: ^1.11.19
  eslint: ^9.39.2
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jest: ^29.12.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  express: ^5.2.1
  globals: ^17.0.0
  husky: ^9.1.7
  identity-obj-proxy: ^3.0.0
  immer: ^11.1.3
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-watch-typeahead: ^3.0.1
  lint-staged: ^16.2.7
  postcss: ^8.5.6
  prettier: 3.7.4
  prompts: ^2.4.2
  react: ^19.2.3
  react-dom: ^19.2.3
  react-is: ^19.2.3
  react-redux: ^9.2.0
  react-router: ^7.11.0
  react-use: ^17.6.0
  reflect-metadata: ^0.2.2
  rimraf: ^6.1.2
  sass: ^1.97.1
  semver: ^7.7.3
  stylelint: ^16.26.1
  stylelint-config-recess-order: ^7.4.0
  stylelint-config-sass-guidelines: ^12.1.0
  stylelint-config-standard: ^39.0.1
  stylelint-config-standard-scss: ^16.0.0
  stylelint-order: ^7.0.1
  tinybench: ^6.0.0
  type-fest: ^5.3.1
  typeorm: ^0.3.28
  typescript: 5.9.3
  typescript-eslint: ^8.53.0
  typescript-plugin-css-modules: ^5.2.0
  vite: ^7.3.0
  vite-plugin-checker: ^0.12.0
  vite-tsconfig-paths: ^6.0.3
  web-vitals: ^5.1.0
  whatwg-fetch: ^3.6.20
  winston: ^3.19.0
  winston-daily-rotate-file: ^5.0.0

catalogMode: prefer

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - less
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild

publicHoistPattern:
  - '*eslint*'

workspaceConcurrency: 0
