packages:
  - configs/*
  - packages/*
  - projects/*
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - less
  - unrs-resolver
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
publicHoistPattern:
  - '*eslint*'
workspaceConcurrency: 0
