packages:
  - configs/*
  - packages/*
  - projects/*
ignoredBuiltDependencies:
  - '@parcel/watcher'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
publicHoistPattern:
  - '*eslint*'
workspaceConcurrency: 0
