name: Build Lint Test

on:
  push:
    branches:
      - '**'
      - '!changelog'
      - '!changelog/*'
      - '!docs'
      - '!docs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup node modules
        run: npm ci

      - name: Build packages and projects
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup node modules
        run: npm ci

      - name: Build scripts
        run: npm run build-scripts

      - name: Build packages
        run: npm run build-packages

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup node modules
        run: npm ci

      - name: Build scripts
        run: npm run build-scripts

      - name: Build packages
        run: npm run build-packages

      - name: Do coverage test
        run: npm run test-full
