name: Build Lint Test

on:
  push:
    branches:
      - '**'
      - '!changelog'
      - '!changelog/*'
      - '!docs'
      - '!docs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages and projects
        run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build scripts
        run: pnpm run build-scripts

      - name: Build packages
        run: pnpm run build-pkgs

      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build scripts
        run: pnpm run build-scripts

      - name: Build packages
        run: pnpm run build-pkgs

      - name: Do coverage test
        run: pnpm run test-full
