name: Lint

on:
    push:
        branches:
            - '**'

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Setup node modules
              run: npm ci

            - name: Lint
              run: npm run lint
